#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XfAutoUpdateDemo.Resource", IsApplication=true)]

namespace XfAutoUpdateDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int collector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_focuse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int dialog_unfocuse = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int iflytek_dialog_image = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int ifltek_cancel = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int ifltek_sure = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int iflytek_update_content = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int iflytek_update_title = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int myButton = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int update_image = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int autoupdate_dialog_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int updateCancelButton = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int updateConfirmButton = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int update_download_progress = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int update_download_success = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
